sudo cp show_client.php /opt/lampp/htdocs
sudo cp appointment_details.php /opt/lampp/htdocs
sudo cp client_page.php /opt/lampp/htdocs
sudo cp client.php /opt/lampp/htdocs
sudo cp consultation_details.php /opt/lampp/htdocs
sudo cp create_client.php /opt/lampp/htdocs
sudo cp create_consultation.php /opt/lampp/htdocs
sudo cp insert_appointment.php /opt/lampp/htdocs
sudo cp insert_client.php /opt/lampp/htdocs
sudo cp insert_consultation.php /opt/lampp/htdocs
sudo cp mark_appointment.php /opt/lampp/htdocs
